### ISSUE TITLE
Action sheets start open and the immediate slide closed.

### ISSUE THREAD

**Issue by jonotron** [jonotron/angular-action-sheet#5]
This is likely a bug in the transition styles. It's easiest to see when you refresh a page with an action sheet that has yet to be revealed. It will appear open, then slide away to hide.

**Comment by chadfawcett** [comment]
@jonotron This would be great if this bug could be fixed soon. Currently I am working on a page that has buttons to add params to the state url in ui-router and it is causing the action sheet to flash open at the push of each button.
